### ISSUE TITLE
Begin-end pairs logic for another pairs

### ISSUE THREAD

**Issue by VaginAY** [EdaphicStudio/SystemVerilog#6]
Good day!

  Is it possible to make begin-end insertion logic for another pairs, such as
  module endmodule
  interface endinterface
  etc...

Best regards,
Alexander

**Comment by EdaphicStudio** [comment]
This one is easy to answer. Yes! All "paired" keywords (like class, module, and interface) will have similar behavior. I wanted to add this feature to see what people think of it (I like it a lot). 

The only one I don't know how to handle is `fork`/`join` as I don't know if you want `join_none` or `join_all`. I will probably be forced to use smart enter on this one and bring up a list. It's clumsy, but I see no better way at the moment.

I'm working on keyword matching right now and plan to get back to this feature afterward. I will release the paired keywords as they get done.

Enabling this behavior is time-consuming as there are many corner cases to test. The caret can be before or after a label. After the end keyword but in a label etc. Getting it to "just work" takes some time and a lot of tests. 

Still, it's a feature I want to see as its essential to how I think when I use SystemVerilog

**Comment by VaginAY** [comment]
Thank you! 
  Smart enter is good idea for fork/join pair.

**Comment by EdaphicStudio** [comment]
All paired keywords, including `fork` is not supported as code completion options. This should solve this issue.
