### ISSUE TITLE
Autocompletion for keywords

### ISSUE THREAD

**Issue by VaginAY** [EdaphicStudio/SystemVerilog#7]
Good day!

  Is it possible to make autocompletion for keywords (always, initial, etc.)?

Best regards,
Alexander

**Comment by EdaphicStudio** [comment]
I'm working on this right now (setting up testing infrastructure). I want to implement smart keyword matching where only keywords relevant to your current scope is presented as a choice. 

That said I might do a quick-and-dirty release where I match against all keywords and then work myself backward. What do you think?

**Comment by VaginAY** [comment]
Good news! We will wait.

**Comment by EdaphicStudio** [comment]
Code completion has come a long way. Still not perfect but better. Please report suggested additions as new bugs
