### ISSUE TITLE
Cross reference between files 

### ISSUE THREAD

**Issue by VaginAY** [EdaphicStudio/SystemVerilog#8]
Good day!

 Inserting a module declared in one file into another do not work.

Best regards,
Alexander

**Comment by EdaphicStudio** [comment]
**I need some more information here**. What are you trying to do? 

The editor should provide a list of modules for auto-completion as you type. If it doesn't then can you try to create a small example to share? 

I don't currently support emacs' AUTO feature, but it's on the medium term feature list.

**Comment by VaginAY** [comment]
I created two files in the project, then in one of them I declared the module.
After that I try to insert name of the first module to second file using autocomplete.
However, the editor did not see the names defined in another file.

**Comment by EdaphicStudio** [comment]
Ok. Makes sense. It's related to the other issue I'm currently debugging. Will make sure to test this issue as well.

**Comment by EdaphicStudio** [comment]
Fixed in BETA8
